Revert "Revert ".NET 8 in proc changes for dedicated linux images""
Azure/azure-functions-docker pull request #1096
Opened 2024-06-07 17:37 UTC by CooperLink

Reverts Azure/azure-functions-docker#1088

Revert revert and bring back dotnet inproc image to Docker Repo. In addition to this I will fix the tag from `dotnet8` -> `dotnet8.0` so that the Linux Platform can select this image

2024-06-07 17:45 UTC, pragnagopa requested changes
update tags to match `8.0` suffix - match the private stamp image map logs :)

2024-06-07 17:54 UTC, CooperLink commented
> update tags to match `8.0` suffix - match the private stamp image map logs :)

Completed

2024-06-07 17:59 UTC, aishwaryabh approved these changes

2024-06-13 03:07 UTC, pragnagopa approved these changes
Please update ReadMe to include new image tags; Also, please add links to MCR docs repo and syndication PRs for completeness

2024-06-13 03:08 UTC, merged