Add chrome headless dependencies to python images
Azure/azure-functions-docker pull request #417
Opened 2021-04-01 17:20 UTC by ahmelsayed

---

Add chrome headless dependencies to 

| Tags                                         |
|----------------------------------------------|
| `3.0`, `3.0-python3.6`                       |
| `3.0-appservice`, `3.0-python3.6-appservice` |
| `3.0-python3.7`                              |
| `3.0-python3.7-appservice`                   |
| `3.0-python3.8`                              |
| `3.0-python3.8-slim`                         |
| `3.0-python3.9`                              |
| `3.0-python3.9-slim`                         |

Closes #407

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

2021-04-01 17:26 UTC, pragnagopa requested changes
Tagging @cooperlink

These changes are needed just for Node image right? If yes, @CooperLink  is actively working on extracting common pieces in docker images to a common base image. If this node specific we can install them just in node images.

2021-04-05 17:00 UTC, ahmelsayed commented
@pragnagopa @CooperLink 

They were initially added just for node, yes. To support puppeteer and playwright. But it seems that some python customers also need them. This is adding them to the python images as well.

2021-04-05 18:15 UTC, pragnagopa approved these changes

2021-04-05 18:15 UTC, pragnagopa commented
@cooperlink - Please see if this can be moved to base image

2021-04-05 18:22 UTC, merged