Adding node16 image
Azure/azure-functions-docker pull request #527
Opened 2021-10-16 00:43 UTC by alrod

2021-10-17 18:32 UTC, balag0 commented on host/4/publish-appservice-stage.yml
> +  - bash: |
Is this the same as above section?

2021-10-18 14:24 UTC, pragnagopa commented on host/4/bullseye/amd64/node/node16/node16-appservice.Dockerfile
> +COPY --from=mcr.microsoft.com/dotnet/sdk:5.0 /usr/share/dotnet /usr/share/dotnet
this is probably not needed. .Net 5 SDK for needed to build V3 runtime

2021-10-18 14:26 UTC, pragnagopa requested changes
no need to install : .Net 5 SDK as this was only needed to build V3

2021-10-18 14:26 UTC, pragnagopa commented
@CooperLink  - please do take a look - more images coming in !

2021-10-20 16:57 UTC, pragnagopa commented on host/4/bullseye/amd64/node/node16/node16.Dockerfile
> +    EXTENSION_BUNDLE_VERSION_V2=2.6.1 && \
please update to latest extension bundles . See https://github.com/Azure/azure-functions-docker/commit/9e6ddfd52a39f554886a808e4cddb9c3771d0f93 for reference

2021-10-20 16:58 UTC, pragnagopa approved these changes
@balag0 - these changes need to part of V4 GA payload as well. Please take a look

2021-10-20 17:02 UTC, balag0 commented on host/4/bullseye/amd64/node/node16/node16-appservice.Dockerfile
> +    EXTENSION_BUNDLE_VERSION_V2=2.6.1 && \
looks like this version has an issue, please update to 2.8.3 (and in other files as well if required)
https://github.com/Azure/azure-functions-docker/commit/9e6ddfd52a39f554886a808e4cddb9c3771d0f93

2021-10-20 17:07 UTC, balag0 commented
> @balag0 - these changes need to part of V4 GA payload as well. Please take a look

@alrod 
Some minor comments. Once merged please work with @kshyju on building the image.

2021-10-20 22:15 UTC, merged