Moving away from nightly image of dotnet/runtime-deps
Azure/azure-functions-docker pull request #561
Opened 2021-11-18 22:39 UTC by kshyju

Fixes #556 

For making the V4 images ready for GA day, we [used ](https://github.com/Azure/azure-functions-docker/pull/537)the nightly images of `dotnet/runtime-deps`. In this PR, we are removing the nightly ones. Thanks to Cooper's refactoring. Only few files need the change.

2021-11-18 22:43 UTC, pragnagopa commented
> Thanks to Cooper's refactoring. Only few files need the change.

💯

2021-11-18 22:44 UTC, pragnagopa approved these changes
💯 @CooperLink  - less number of files changes in the PR

2021-11-18 23:03 UTC, pragnagopa requested changes
Just realized - this needs to updated in the other language composite files too - see  https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/java/java8/java8-composite.template#L4 - for example

Please do string search across the repo so we do not miss any files

2021-11-19 01:07 UTC, kshyju commented
> Just realized - this needs to updated in the other language composite files too - see https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/java/java8/java8-composite.template#L4 - for example
> 
> Please do string search across the repo so we do not miss any files

Thank you! Fixed.

2021-11-19 01:25 UTC, pragnagopa approved these changes

2021-11-19 02:08 UTC, merged