Update LibAppIndicator in V4 to libayatana-appindicator
Azure/azure-functions-docker pull request #743
Opened 2022-07-20 22:25 UTC by CooperLink

https://github.com/Azure/azure-functions-docker/issues/333 identified that LibAppIndicator is deprecated in Bullseye Debian and needs to be replaced with a supported library.  This library needs to be updated to support Chrome Headless.

This PR is building off of the work of @nyds https://github.com/Azure/azure-functions-docker/pull/738/files
Link to Debian Bug Discussion : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

Releasing new Host versions.
[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)

---

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

2022-07-21 07:22 UTC, nyds commented
Hi @CooperLink , thanks for addressing this issue! I've noticed the lines where the dependencies are installed are still commented out.

2022-07-21 16:06 UTC, pragnagopa commented on host/4/bullseye/amd64/node/node14/node14-composite.template
> +#    libxtst6 ca-certificates fonts-liberation libayatana-appindicator3-1 libnss3 lsb-release xdg-utils wget
code is still commented. Also, lets add this library on need basis - not all languages / Cx scenarios need it. 

Lets go ahead and add to node and dotnet images only. Lets see if Cx ask for python and dotnet-isolated

2022-07-21 16:06 UTC, pragnagopa requested changes
Uncomment the code  - reduce the scope of adding this library - to node and dotnet images only

2022-08-14 10:13 UTC, rameziophobia commented
made a PR with an uncommented version of the changes. https://github.com/Azure/azure-functions-docker/pull/743

2022-12-28 17:36 UTC, closed without merging