Removing Powershell 6 from build.yml
Azure/azure-functions-docker pull request #919
Opened 2023-06-20 18:39 UTC by VpOfEngineering

Removing Powershell 6 references from build and publish.

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [x] New Unit tests were added for the changes made and CI is passing.

2023-06-20 18:46 UTC, pragnagopa commented on host/3.0/powershell-build.yml
>        - host/3.0/buster/amd64/powershell/powershell7/*
please remove powershell 7 as well

2023-06-20 18:46 UTC, pragnagopa requested changes
Please remove V3 powershell  7 as well

2023-06-20 18:48 UTC, pragnagopa commented
please delete from core-tools publish as well

2023-06-21 15:53 UTC, pragnagopa approved these changes

2023-06-22 16:06 UTC, CooperLink approved these changes

2023-06-22 16:09 UTC, merged