Add images for Java 21
Azure/azure-functions-docker pull request #966
Opened 2023-09-28 18:55 UTC by kamperiadis

- Add v4 images for Java 21
- Update files to include Java 21:
  - core-tools-publish.yml
  - java-build.yml
  - publish-appservice-stage-sovereign-clouds.yml
  - publish-appservice-stage.yml
  - publish.yml

---

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [] If applicable, the PR references the bug/issue that it fixes in the description.
- [] New Unit tests were added for the changes made and CI is passing.

2023-10-02 14:58 UTC, kaibocai approved these changes, later dismissed
LGTM thank you!

2023-10-02 15:05 UTC, CooperLink requested changes
Please add the new image to our republish pipeline : https://github.com/Azure/azure-functions-docker/blob/dev/host/4/republish.yml

2023-10-02 19:26 UTC, CooperLink submitted a review, later dismissed
LGTM

2023-10-04 13:24 UTC, pragnagopa commented on host/4/bullseye/amd64/java/java21/java21-build.Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk:6.0
as bulleseye will be retiring soon, new images need to be on book work.

@CooperLink - is that possible?

2023-10-04 13:25 UTC, pragnagopa requested changes
Need to discuss how to move to bookwork

2023-10-10 19:10 UTC, CooperLink commented on host/4/bullseye/amd64/java/java21/java21-composite.template
> +ARG JAVA_VERSION
Currently the host composite image is based on Bullseye so for now it likely makes more sense to replace this with an -appservice image. I can show Kirstyn how to do this. 
This is necessary to get Host on bookworm
@pragnagopa

2023-10-13 22:33 UTC, pragnagopa submitted a review, later dismissed

2023-10-18 21:29 UTC, CooperLink approved these changes

2023-10-18 21:30 UTC, merged